apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    environment: production
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
        environment: production
    spec:
      volumes:
        - name: deployment-config
          configMap:
            name: my-deployment
      containers:
        - name: posimage
          image: gcr.io/app-mod-gebu-trainees/posimage:latest
          ports:
            - containerPort: 8080
        - name: databaseimage
          image: gcr.io/app-mod-gebu-trainees/databaseimage:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: db
      port: 3306
      targetPort: 3306
