apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    environment: production
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:
        - name: deployment-config
          configMap:
            name: my-deployment
      containers: []
