apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pos1
  namespace: pos1
spec:
  selector:
    matchLabels:
      app: myapp-pos1
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-pos1
    spec:
      containers:
        - name: posimage
          image: gcr.io/app-mod-gebu-trainees/posimage:latest
          ports:
            - containerPort: 8080
        - name: databaseimage
          image: gcr.io/app-mod-gebu-trainees/databaseimage:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-pos1
  namespace: pos1
spec:
  type: LoadBalancer
  selector:
    app: myapp-pos1
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: db
      port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-pos2
  namespace: pos2
spec:
  selector:
    matchLabels:
      app: myapp-pos2
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-pos2
    spec:
      containers:
        - name: posimage
          image: gcr.io/app-mod-gebu-trainees/posimage:latest
          ports:
            - containerPort: 8080
        - name: databaseimage
          image: gcr.io/app-mod-gebu-trainees/databaseimage:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-pos2
  namespace: pos2
spec:
  type: LoadBalancer
  selector:
    app: myapp-pos2
  ports:
    - name: web
      port: 8080
      targetPort: 8080
    - name: db
      port: 3306
      targetPort: 3306
